In [1]:
import pandas as pd
import numpy as np

In [2]:
# import passengers data created in Italians_data_exploration.ipynb
csv = open('./data/sicily_passengers.csv')
df = pd.read_csv(csv)

In [3]:
df.head()

,Unnamed: 0,LastName,FirstName,Age,Occupation,Literacy,CountryofOrigin,CityTownofLastResidence,DestinationCityTown,TransitTravelCompartment,ManifestID,Province,ShipName,Port,Arrival
0,0,BUONGIORNO,ANTONIO,49,BLACKSMITH,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236,Agrigento,EMS,NAPLES,12/29/1892
1,1,BUONGIORNO,GIUSEPPE,60,BLACKSMITH,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236,Agrigento,EMS,NAPLES,12/29/1892
2,2,CARUSO,FRANCESCA,Infant in months: 10,INFANT,NO,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236,Agrigento,EMS,NAPLES,12/29/1892
3,3,CARUSO,FRANCESCO,03,"CHILD, YOUNGSTER",NO,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236,Agrigento,EMS,NAPLES,12/29/1892
4,4,CARUSO,ROSA,38,WIFE,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236,Agrigento,EMS,NAPLES,12/29/1892

In [4]:
df = df.drop(columns="Unnamed: 0")

In [5]:
df.head()

,LastName,FirstName,Age,Occupation,Literacy,CountryofOrigin,CityTownofLastResidence,DestinationCityTown,TransitTravelCompartment,ManifestID,Province,ShipName,Port,Arrival
0,BUONGIORNO,ANTONIO,49,BLACKSMITH,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236,Agrigento,EMS,NAPLES,12/29/1892
1,BUONGIORNO,GIUSEPPE,60,BLACKSMITH,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236,Agrigento,EMS,NAPLES,12/29/1892
2,CARUSO,FRANCESCA,Infant in months: 10,INFANT,NO,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236,Agrigento,EMS,NAPLES,12/29/1892
3,CARUSO,FRANCESCO,03,"CHILD, YOUNGSTER",NO,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236,Agrigento,EMS,NAPLES,12/29/1892
4,CARUSO,ROSA,38,WIFE,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236,Agrigento,EMS,NAPLES,12/29/1892

In [6]:
df.sort_values('DestinationCityTown')

,LastName,FirstName,Age,Occupation,Literacy,CountryofOrigin,CityTownofLastResidence,DestinationCityTown,TransitTravelCompartment,ManifestID,Province,ShipName,Port,Arrival
19316,LEONE,ROSARIA,04,DOMESTIC,NO,ITALY,VALLEDOLMO,--PORT,Staying in the USA [Transit]; Steer[Travel],83150,Palermo,BOLIVIA,PALERMO,01/30/1899
38880,VICARI,FRANCESCA,15,DAUGHTER,NO,ITALY,VALLEDOLMO,--PORT,Staying in the USA [Transit]; Steer[Travel],83150,Palermo,BOLIVIA,PALERMO,01/30/1899
19812,LIPARI,ANTONINA,43,HOUSEWIFE,NO,ITALY,VALLEDOLMO,-MORRIS NY,Staying in the USA [Transit]; Steer[Travel],83555,Palermo,VICTORIA,NAPLES,12/17/1900
33337,SANTOMARE,ARMANDA,02,FARMER,NO,ITALY,CATANIA,0,Staying in the USA [Transit]; Steer[Travel],83530,Catania,HESPERIA,NAPLES,10/26/1900
4295,BRUVA,SERAFINA,36,HOUSEWIFE,NO,ITALY,CATANIA,0,Staying in the USA [Transit]; Steer[Travel],83530,Catania,HESPERIA,NAPLES,10/26/1900
31790,ROMEO,VENTIMINA,11,FARMER,NO,ITALY,CATANIA,0,Staying in the USA [Transit]; Steer[Travel],83530,Catania,HESPERIA,NAPLES,10/26/1900
31767,ROMEO,ELENA,Infant in months: 08,FARMER,NO,ITALY,CATANIA,0,Staying in the USA [Transit]; Steer[Travel],83530,Catania,HESPERIA,NAPLES,10/26/1900
27418,PARISI,EUGENIA,23,SEAMSTRESS,READ & WRITE,ITALY,CATANIA,0,Staying in the USA [Transit]; Steer[Travel],83530,Catania,HESPERIA,NAPLES,10/26/1900
27449,PARISI,NATALA,65,SEAMSTRESS,NO,ITALY,CATANIA,0,Staying in the USA [Transit]; Steer[Travel],83530,Catania,HESPERIA,NAPLES,10/26/1900
2763,BATTAGLIA,SALVATORE,51,LABORER,NO,ITALY,VALLEDOLMO,ADAM-PA,Staying in the USA [Transit]; Steer[Travel],83196,Palermo,ALSATIA,NAPLES,05/15/1899
23975,MESSINA,GIUSEPPE,38,SHOEMAKER,UNKNOWN,ITALY,ALIMENA,AIZAO,Staying in the USA [Transit]; Steer[Travel],235,Palermo,NEUSTRIA,MARSEILLES & NAPLES,07/24/1895
298,PACINO,ANNA,22,INFANT,READ & WRITE,ITALY,PALAZZO ADRIANO,ALABAMA,Staying in the USA [Transit]; Cabin Passenger ...,82171,Palermo,BIRMANIA,NAPLES,08/16/1892
307,PARRINO,GIOVANNI,30,CARPENTER,READ & WRITE,ITALY,PALAZZO ADRIANO,ALABAMA,Staying in the USA [Transit]; Cabin Passenger ...,82171,Palermo,BIRMANIA,NAPLES,08/16/1892
14488,GAMBINO,TOMMASO,08,"CHILD, YOUNGSTER",UNKNOWN,ITALY,PALERMO,ALBAMA,Staying in the USA [Transit]; Steer[Travel],452,Palermo,INIZIATIVA,NAPLES,07/13/1891
14476,GAMBINO,GASPARE,38,SHOEMAKER,UNKNOWN,ITALY,TORRETTA,ALBAMA,Staying in the USA [Transit]; Steer[Travel],452,Palermo,INIZIATIVA,NAPLES,07/13/1891
13536,FIORE,FRANCESCO,21,COUNTRY MAN,NO,ITALY,CACCAMO,ALBANY,Staying in the USA [Transit]; Steer[Travel],83187,Palermo,KAISER WILHELM II,GENOA,04/30/1899
22363,MANTICA,GIUSEPPE,11,FARMER,READ & WRITE,ITALY,MESSINA,ALBANY,Staying in the USA [Transit]; Steer[Travel],83137,Messina,TARTAR PRINCE,GENOA,12/18/1898
22362,MANTICA,GIOVANNI,Infant in months: 07,FARMER,NO,ITALY,MESSINA,ALBANY,Staying in the USA [Transit]; Steer[Travel],83137,Messina,TARTAR PRINCE,GENOA,12/18/1898
22361,MANTICA,GIOVANNA,Infant in months: 05,FARMER,NO,ITALY,MESSINA,ALBANY,Staying in the USA [Transit]; Steer[Travel],83137,Messina,TARTAR PRINCE,GENOA,12/18/1898
22360,MANTICA,CARMELA,13,HOUSEWIFE,READ & WRITE,ITALY,MESSINA,ALBANY,Staying in the USA [Transit]; Steer[Travel],83137,Messina,TARTAR PRINCE,GENOA,12/18/1898
22359,MANTICA,ALBERTO,16,LABORER,READ & WRITE,ITALY,MESSINA,ALBANY,Staying in the USA [Transit]; Steer[Travel],83137,Messina,TARTAR PRINCE,GENOA,12/18/1898
31834,ROSARIO,GIUDITTA,50,CARPENTER,READ & WRITE,ITALY,CATANIA,ALBANY,Staying in the USA [Transit]; Steer[Travel],83553,Catania,VINCENZO FLORIO,NAPLES,12/20/1900
29820,PUCCIO,NICOLA,67,BAKER,NO,ITALY,PALERMO,ALBANY,Staying in the USA [Transit]; Steer[Travel],83524,Palermo,MANILLA,NAPLES,10/08/1900
33838,SCARDINA,GIUSEPPE,20,JOINER,NO,ITALY,BAGHERIA,ALBANY,Staying in the USA [Transit]; Steer[Travel],83401,Palermo,FURST BISMARCK,GENOA,03/12/1900
8371,COSENTINO,NUNZIA,30,HOUSEWIFE,NO,ITALY,LIPARI,ALBANY,Staying in the USA [Transit]; Steer[Travel],83452,Messina,WERRA,GENOA,05/17/1900
23500,MAZZARELLA,GAETANO,37,MASON,NO,ITALY,BAGHERIA,ALBANY,Staying in the USA [Transit]; Steer[Travel],83401,Palermo,FURST BISMARCK,GENOA,03/12/1900
22364,MANTICA,LETTERIA,03,FARMER,NO,ITALY,MESSINA,ALBANY,Staying in the USA [Transit]; Steer[Travel],83137,Messina,TARTAR PRINCE,GENOA,12/18/1898
22365,MANTICA,MARIA,08,FARMER,READ & WRITE,ITALY,MESSINA,ALBANY,Staying in the USA [Transit]; Steer[Travel],83137,Messina,TARTAR PRINCE,GENOA,12/18/1898
12386,FALANGA,GIUSEPPE,19,PACKER,READ & WRITE,ITALY,LIPARI,ALBANY,Staying in the USA [Transit]; Steer[Travel],83452,Messina,WERRA,GENOA,05/17/1900
17963,JACONO,MARIA,23,HOUSEWIFE,NO,ITALY,LIPARI,ALBANY,Staying in the USA [Transit]; Steer[Travel],83452,Messina,WERRA,GENOA,05/17/1900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35819,SPERANZA,ANGELA,02,HOUSEWIFE,NO,ITALY,SERRADIFALCO,WINNIPEG CAN,Staying in the USA [Transit]; Steer[Travel],83528,Caltanissetta,WERRA,GENOA & NAPLES,10/20/1900
35821,SPERANZA,GIUSEPPE,04,HOUSEWIFE,NO,ITALY,SERRADIFALCO,WINNIPEG CAN,Staying in the USA [Transit]; Steer[Travel],83528,Caltanissetta,WERRA,GENOA & NAPLES,10/20/1900
35822,SPERANZA,MICHELE,32,HOUSEWIFE,READ & WRITE,ITALY,SERRADIFALCO,WINNIPEG CAN,Staying in the USA [Transit]; Steer[Travel],83528,Caltanissetta,WERRA,GENOA & NAPLES,10/20/1900
10793,DIBENEDETTO,GAETANO,50,SEAMSTRESS,NO,ITALY,CORLEONE,WISCONSIN,Staying in the USA [Transit]; Steer[Travel],83486,Palermo,EMS,GENOA,07/19/1900
14323,GALIOTO,GIUSEPPE,39,COUNTRY MAN,NO,ITALY,BAGHERIA,WISCONSIN,Staying in the USA [Transit]; Steer[Travel],83438,Palermo,ARCHIMEDE,NAPLES,04/23/1900
33591,SAVONE,FILIPPO,36,SHOEMAKER,READ & WRITE,ITALY,SCIARA,WORCESTER,Staying in the USA [Transit]; Steer[Travel],83216,Palermo,SAALE,GENOA,06/22/1899
9264,D,CATERINA,30,HOUSEKEEPER,READ & WRITE,ITALY,RIBERA,WY,Staying in the USA [Transit]; Steer[Travel],83485,Agrigento,LA BRETAGNE,HAVRE,07/16/1900
3274,BERTINO,MATTEA,56,DAY WORKER,READ & WRITE,ITALY,RIBERA,WY,Staying in the USA [Transit]; Steer[Travel],83485,Agrigento,LA BRETAGNE,HAVRE,07/16/1900
25903,NAVARRA,SALVATORE,19,COUNTRY MAN,NO,ITALY,TRABIA,YOHUGSTON-PA,Staying in the USA [Transit]; Steer[Travel],83393,Palermo,EMS,GENOA,02/23/1900
20091,LO GRASSO,PIETRO,04,"NIECE, NEPHEW",NO,ITALY,BAGHERIA,YONIGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83451,Palermo,VICTORIA,NAPLES,05/16/1900
20090,LO GRASSO,PIETRO,03,"NIECE, NEPHEW",NO,ITALY,BAGHERIA,YONIGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83451,Palermo,VICTORIA,NAPLES,05/16/1900
20089,LO GRASSO,ORSOLA,07,"NIECE, NEPHEW",NO,ITALY,BAGHERIA,YONIGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83451,Palermo,VICTORIA,NAPLES,05/16/1900
20088,LO GRASSO,MADDALENA,03,"NIECE, NEPHEW",NO,ITALY,BAGHERIA,YONIGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83451,Palermo,VICTORIA,NAPLES,05/16/1900
39549,ZICANO,FRANCESCA,33,HOUSEWIFE,READ & WRITE,ITALY,BAGHERIA,YONIGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83451,Palermo,VICTORIA,NAPLES,05/16/1900
39550,ZICANO,ROSA,25,HOUSEWIFE,READ & WRITE,ITALY,BAGHERIA,YONIGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83451,Palermo,VICTORIA,NAPLES,05/16/1900
20085,LO GRASSO,FRANCESCO,01,"NIECE, NEPHEW",NO,ITALY,BAGHERIA,YONIGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83451,Palermo,VICTORIA,NAPLES,05/16/1900
20022,LO BUGLIO,ANTONIO,35,LABORER,NO,ITALY,BAGHERIA,YONIGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83451,Palermo,VICTORIA,NAPLES,05/16/1900
13625,FIZANO,CARMELO,28,LABORER,READ & WRITE,ITALY,BAGHERIA,YONIGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83451,Palermo,VICTORIA,NAPLES,05/16/1900
7778,COMASCELLO,FRANCESCO,52,LABORER,NO,ITALY,BAGHERIA,YONIGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83451,Palermo,VICTORIA,NAPLES,05/16/1900
20087,LO GRASSO,GIUSEPPE,04,"NIECE, NEPHEW",NO,ITALY,BAGHERIA,YONIGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83451,Palermo,VICTORIA,NAPLES,05/16/1900
13031,FERRANTE,GIUSEPPE,20,"GARDENER, GROWER",READ & WRITE,ITALY,PALERMO,YOUNGSTON,Staying in the USA [Transit]; Steer[Travel],83232,Palermo,EMS,GENOA,07/12/1899
25253,MORELLI,SALVATOR,18,SHOEMAKER,READ & WRITE,ITALY,PALERMO,YOUNGSTON,Staying in the USA [Transit]; Steer[Travel],83232,Palermo,EMS,GENOA,07/12/1899
20084,LO GRASO,PIETRO,29,LABORER,READ & WRITE,ITALY,BAGHERIA,YOUNGSTON,Staying in the USA [Transit]; Steer[Travel],83351,Palermo,CALIFORNIA,NAPLES,10/29/1899
4426,BUTTILLO,FRANCESCO,47,COUNTRY MAN,READ & WRITE,ITALY,BAGHERIA,YOUNGSTOWN,Staying in the USA [Transit]; Steer[Travel],83341,Palermo,ARCHIMEDE,NAPLES,10/09/1899
22483,MARCHESANO,LUCA,39,COUNTRY MAN,NO,ITALY,CACCAMO,YOUNGSTOWN,Staying in the USA [Transit]; Steer[Travel],83182,Palermo,ALLER,GENOA,04/20/1899
3278,BERTOLA,ROSARIO,40,COUNTRY MAN,READ & WRITE,ITALY,CERDA,YOUNGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83444,Palermo,SPARTAN PRINCE,NAPLES,05/06/1900
13356,FICANO,GIUSEPPE,Infant in months: 10,LABORER,READ & WRITE,ITALY,BAGHERIA,YOUNGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83540,Palermo,NEUSTRIA,MARSEILLES,11/12/1900
13357,FICANO,SALVATORE,36,LABORER,READ & WRITE,ITALY,BAGHERIA,YOUNGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83540,Palermo,NEUSTRIA,MARSEILLES,11/12/1900
29454,PRESTGIACOMO,MICHELE,23,LABORER,READ & WRITE,ITALY,CERDA,YOUNGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83444,Palermo,SPARTAN PRINCE,NAPLES,05/06/1900
6995,CI-CIOLA,MARIA,29,LABORER,READ & WRITE,ITALY,BAGHERIA,YOUNGSTOWN OH,Staying in the USA [Transit]; Steer[Travel],83540,Palermo,NEUSTRIA,MARSEILLES,11/12/1900

In [7]:
df.axes

[RangeIndex(start=0, stop=39725, step=1),
 Index(['LastName', 'FirstName', 'Age', 'Occupation', 'Literacy',
        'CountryofOrigin', 'CityTownofLastResidence', 'DestinationCityTown',
        'TransitTravelCompartment', 'ManifestID', 'Province', 'ShipName',
        'Port', 'Arrival'],
       dtype='object')]

In [8]:
dest = df['DestinationCityTown'].unique()

In [9]:
dest_df = pd.DataFrame(
                {'DestRaw' : dest,
                 'Dest' : dest})

In [10]:
dest_df

                  DestRaw                  Dest
0                NEW YORK              NEW YORK
1          NEW-ORLEANS-LA        NEW-ORLEANS-LA
2             NEW-ORLEANS           NEW-ORLEANS
3                     USA                   USA
4            PHILADELPHIA          PHILADELPHIA
5                  BOSTON                BOSTON
6                 CHICAGO               CHICAGO
7                  KANSAS                KANSAS
8             NEW ORLEANS           NEW ORLEANS
9                   TEXAS                 TEXAS
10          SAN FRANCISCO         SAN FRANCISCO
11                BUFFALO               BUFFALO
12                ALABAMA               ALABAMA
13               NEW YROK              NEW YROK
14              SAN LOUIS             SAN LOUIS
15              LOUISIANA             LOUISIANA
16           PITTSBURG PA          PITTSBURG PA
17             BUFFALO NY            BUFFALO NY
18             CHICAGO IL            CHICAGO IL
19           WESTERLEY RI          WESTERLEY RI
20               BROOKLYN              BROOKLYN
21             HOUSTON-TX            HOUSTON-TX
22            ELEONORE-PA           ELEONORE-PA
23            BROOKLYN NY           BROOKLYN NY
24            MINNEAPOLIS           MINNEAPOLIS
25              BOSTON-MA             BOSTON-MA
26              PITTSBURG             PITTSBURG
27                 ALTONA                ALTONA
28              ROCHESTER             ROCHESTER
29           ROCHESTER-NY          ROCHESTER-NY
..                    ...                   ...
906              HOMESTEA              HOMESTEA
907              HOMOSTEA              HOMOSTEA
908          CLEVELAND OK          CLEVELAND OK
909             S ANTONIO             S ANTONIO
910             MIDDEKEAN             MIDDEKEAN
911                AMATRA                AMATRA
912          PORT-CHESTER          PORT-CHESTER
913            MILFORD PA            MILFORD PA
914           BRADFORD-CT           BRADFORD-CT
915  SUSPENSION BRIDGE NY  SUSPENSION BRIDGE NY
916                MOUNT-                MOUNT-
917           MIDLETON CT           MIDLETON CT
918           ST.LOUIS-MA           ST.LOUIS-MA
919       NEW  ORLEANS LA       NEW  ORLEANS LA
920          WATERBURG CT          WATERBURG CT
921               SCIACCA               SCIACCA
922         PROVIDENCE MA         PROVIDENCE MA
923             MT MORRIS             MT MORRIS
924          PENSACOLA-FL          PENSACOLA-FL
925            SMITHON PA            SMITHON PA
926          NAPOLEONVILL          NAPOLEONVILL
927         JOHNNSTOWN PA         JOHNNSTOWN PA
928             BROOKLYNG             BROOKLYNG
929               NEW ARK               NEW ARK
930            MADISON NJ            MADISON NJ
931     OKLAHOMA CITY OK.     OKLAHOMA CITY OK.
932               ST.JOHN               ST.JOHN
933         CLEVELAND OH.         CLEVELAND OH.
934            MERIDEN-CT            MERIDEN-CT
935            ST.PAUL-MN            ST.PAUL-MN

[936 rows x 2 columns]

In [11]:
dest_df.to_csv('./data/destinations_raw.csv')

In [13]:
df['TransitTravelCompartment'].value_counts()

Staying in the USA [Transit]; Steer[Travel]                     39289
Staying in the USA [Transit]; Cabin Passenger [Travel]            421
Staying in the USA [Transit]; Stowaway [Travel]                    10
Return trip to USA - non US Citizen [Transit]; Steer[Travel]        5
Name: TransitTravelCompartment, dtype: int64