In [1]:
import pandas as pd
import numpy as np

In [2]:
csv1 = open('./data/italians_parta.csv', 'r', newline='')
csv2 = open('./data/italians_partb.csv', 'r', newline='')
csv3 = open('./data/italians_partc.csv', 'r', newline='')

In [3]:
df1 = pd.read_csv(csv1)
df2 = pd.read_csv(csv2)
df3 = pd.read_csv(csv3)

In [4]:
# combine the three passenger files
df = df1.append([df2,df3], sort=False)
df.head()

,LastName,FirstName,Age,Occupation,Literacy,CountyofOrigin,CityTownofLastResidence,DestinationCityTown,TransitTravelCompartment,ManifestID
0,ZERONI,CARLO,39,MANUFACTURER,READ & WRITE,ITALY,MIDDLESEX,CALIFORNIA,Return trip to USA - non US Citizen [Transit];...,82279.0
1,ARATA,ANNA,16,FARMER,UNKNOWN,ITALY,SAN-FRANCISCO,SAN-FRANCISCO,Return trip to USA - non US Citizen [Transit];...,80120.0
2,BRILLANTI,SALVATORE,34,FISHERMAN,NO,ITALY,ITALY,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82224.0
3,BUONGIORNO,ANTONIO,49,BLACKSMITH,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0
4,BUONGIORNO,GIUSEPPE,60,BLACKSMITH,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0

In [13]:
df['CityTownofLastResidence'].value_counts()

U                    383977
NAPOLI                10717
PALERMO                6644
NEW YORK               6293
TERMINI                4276
UNKNOWN                3958
SCIACCA                3527
MESSINA                3037
AVELLINO               2282
PHILADELPHIA           2245
CAMPOBASSO             1915
POTENZA                1888
SALERNO                1579
NICASTRO               1403
COSENZA                1397
CORLEONE               1371
CEFALU                 1319
VALLEDOLMO             1311
ISERNIA                1283
TERMINI-IMERESE        1206
NICOSIA                1166
LIPARI                 1135
MONTEMAGGIORE          1128
TORINO                 1097
TRABIA                 1093
NAPLES                 1062
CASERTA                1051
MARINEO                1047
BOSTON                 1043
BROOKLYN               1030
                      ...
FABENE                    1
ALESSO-DI-C.              1
DIANO                     1
SORTANO                   1
VALDENGI                  1
GRANI-GNE                 1
CARONITI                  1
VILLA CASTELLI            1
GUARDA-PERTICARA          1
PIETROTERRA               1
CASOOLO                   1
CESANI                    1
AURANO NUSCO              1
ALIMINOSA                 1
BAZOUONE                  1
CORNPADALERNA             1
GUILMI                    1
ALBOREGGIO                1
CIRCETTO                  1
GIOVENE                   1
CERTEROLI                 1
MADONNA DI CIRANE         1
COCCAMIO                  1
TEORI                     1
OLI---                    1
ROCCANUO                  1
ALVI--NANELLO             1
PREDGANA                  1
S ELIA P                  1
FOSATO                    1
Name: CityTownofLastResidence, Length: 27334, dtype: int64

In [14]:
df['DestinationCityTown'].value_counts()

NEW YORK               419099
USA                    118909
BROOKLYN                15187
PHILADELPHIA            14521
BOSTON                  12447
CHICAGO                  9532
NEW-YORK                 5639
BUFFALO                  5613
NEW-ORLEANS              5324
CALIFORNIA               5078
BROOKLYN NY              4918
SAN-FRANCISCO            4369
PHILADELPHIA PA          4106
BOSTON MA                4102
PITTSBURG                3820
BOSTON-MA                3411
PROVVIDENCE              2974
PITTSBURGH               2722
PENNSYLVANIA             2694
NEWARK                   2668
PROVIDENCE               2460
SAN FRANCISCO            2448
PITTSBURG PA             2345
CHICAGO IL               2312
PHILADELPHIA-PA          1751
BALTIMORE                1746
CHICAGO-IL               1727
PA                       1656
PROVIDENCE RI            1443
MONTREAL                 1376
                        ...
W TROIA NY                  1
CARLEGATE-UT                1
CORK                        1
LENVENWORTH                 1
WALLING                     1
LAICHBURGH PA               1
OLO-FORGE                   1
NE ORLEANS LA               1
ZURBAN                      1
DUPORT                      1
CLINTON WV                  1
OLOKA (INDIAN TERRI         1
VULCAN-MA                   1
LAMICEL MASS                1
GICORYMAS (MEXIQUE)         1
CARRTON-IL                  1
BEISSEINER-MI               1
MERIDA-FLORIDA              1
IRON-BELT                   1
VOINNEBURG                  1
BORGARELLO                  1
MOULTAN                     1
ONETA                       1
SCHENUTAD-NY                1
-CITY                       1
DAGOS MINES PA              1
SILVER PLAMER               1
KANSAS-CITY-KS              1
EVANS                       1
KRESS                       1
Name: DestinationCityTown, Length: 12713, dtype: int64

In [15]:
df['ManifestID'].value_counts()

81903.0     1709
81818.0     1456
81866.0     1452
82765.0     1445
81189.0     1436
81877.0     1334
81177.0     1323
242.0       1319
81535.0     1298
83503.0     1297
81855.0     1270
83188.0     1268
81118.0     1254
83332.0     1233
81839.0     1226
83058.0     1220
896.0       1205
83459.0     1204
81199.0     1199
81847.0     1175
81868.0     1175
83439.0     1166
81194.0     1160
83471.0     1155
83532.0     1136
82310.0     1127
31.0        1124
83461.0     1122
82919.0     1121
83054.0     1116
            ...
901016.0       1
900974.0       1
900944.0       1
10396.0        1
36456.0        1
101.0          1
9779.0         1
9031.0         1
35684.0        1
9793.0         1
58064.0        1
9821.0         1
44073.0        1
902982.0       1
902424.0       1
8953.0         1
8960.0         1
35842.0        1
30233.0        1
901807.0       1
901793.0       1
35946.0        1
9001.0         1
901721.0       1
9806.0         1
901719.0       1
901473.0       1
901416.0       1
9803.0         1
36432.0        1
Name: ManifestID, Length: 4483, dtype: int64

In [5]:
df['ManifestID'].nunique()

4483

In [6]:
# list of Communes with assoicated Province in Sicily
communes = pd.read_csv('./data/communes_sicily.csv')

In [7]:
communes.head()

            Commune Province Population
0             Acate   Ragusa      9,574
1    Aci Bonaccorsi  Catania      3,200
2      Aci Castello  Catania     18,122
3        Aci Catena  Catania     28,749
4  Aci Sant'Antonio  Catania     17,270

In [8]:
# make commune name uppercase to make passenger data
communes['Commune'] = communes['Commune'].str.upper();

In [9]:
df['CityTownofLastResidence'].isin(communes['Commune']).value_counts() #39,725 immigrants from Sicily

False    729149
True      39725
Name: CityTownofLastResidence, dtype: int64

In [16]:
# create new df of only Sicilian passengers
sicilydf = df[df['CityTownofLastResidence'].isin(communes['Commune']) == True]
sicilydf

,LastName,FirstName,Age,Occupation,Literacy,CountyofOrigin,CityTownofLastResidence,DestinationCityTown,TransitTravelCompartment,ManifestID
3,BUONGIORNO,ANTONIO,49,BLACKSMITH,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0
4,BUONGIORNO,GIUSEPPE,60,BLACKSMITH,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0
5,CARUSO,FRANCESCA,Infant in months: 10,INFANT,NO,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0
6,CARUSO,FRANCESCO,03,"CHILD, YOUNGSTER",NO,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0
7,CARUSO,ROSA,38,WIFE,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0
83,ATTANASIO,GIUSEPPE,21,LABORER,UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],80591.0
118,CORRAO,VINCENZO,23,CARPENTER,UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],80591.0
121,CUBILLO,ROSARIO,40,UNKNOWN,UNKNOWN,ITALY,MESSINA,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],63.0
125,DACQUISTO,LORENZO,22,BLACKSMITH,UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],80591.0
134,DERASE,LUIGI,Unknown,UNKNOWN,UNKNOWN,ITALY,MESSINA,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],63.0
137,DICNCANA,FLAGIO,18,UNKNOWN,UNKNOWN,ITALY,MESSINA,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],63.0
145,GARAFALO,FRANCESCO,33,BLACKSMITH,UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],80591.0
176,MAIORANA,VITO,16,LABORER,UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],80591.0
202,PELLEGRINO,GAETANO,Unknown,UNKNOWN,UNKNOWN,ITALY,MESSINA,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],63.0
217,RICCIO,ANTONIO,Unknown,UNKNOWN,UNKNOWN,ITALY,MESSINA,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],63.0
250,AGNELLO,ANTONINO,08,"CHILD, YOUNGSTER",UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Cabin Passenger ...,108.0
251,AGNELLO,FRANCESCO,02,"CHILD, YOUNGSTER",UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Cabin Passenger ...,108.0
252,AGNELLO,FRANCESCO,39,COUNTRY MAN,UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Cabin Passenger ...,108.0
253,AGNELLO,ISIDORO,06,"CHILD, YOUNGSTER",UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Cabin Passenger ...,108.0
254,AGOSTA,ALFONSO,20,FARMER,UNKNOWN,ITALY,POGGIOREALE,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
255,AGOSTA,GIUSEPPE,24,FARMER,NO,ITALY,POGGIOREALE,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
259,AMATO,GAETANO,28,FARMER,UNKNOWN,ITALY,POGGIOREALE,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
260,AMORE,CARLO,22,CARPENTER,UNKNOWN,ITALY,PALERMO,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
261,ANASTASI,PIETRO,34,DOMESTIC,UNKNOWN,ITALY,MESSINA,NEW YORK,Staying in the USA [Transit]; Cabin Passenger ...,468.0
264,AVVOCATO,ROSARIO,38,FARMER,NO,ITALY,SALAPARUTA,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
268,BARONE,FRANCESCA,07,"CHILD, YOUNGSTER",UNKNOWN,ITALY,CACCAMO,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
269,BARONE,VINCENZA,10,"CHILD, YOUNGSTER",UNKNOWN,ITALY,CACCAMO,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
273,BASILE,NUNZIATA,21,LABORER,UNKNOWN,ITALY,USTICA,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
274,BENFANTE,ANTONINO,24,CARTER,READ & WRITE,ITALY,MENFI,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
277,BIONDOLILLO,LUCIA,21,HOUSE WOMAN,UNKNOWN,ITALY,ALIA,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
...,...,...,...,...,...,...,...,...,...,...
97748,ZUCCHERO,CONCETTA,29,FARMER,UNKNOWN,ITALY,MARINEO,NEW YORK,Staying in the USA [Transit]; Steer[Travel],81352.0
97749,ZUCCHERO,CONCETTA,36,FARMER,NO,ITALY,MARINEO,NEW YORK,Staying in the USA [Transit]; Steer[Travel],82923.0
97752,ZUCCHERO,GIUSEPPA,12,DOMESTIC,NO,ITALY,SCIARA,ONEIDA NY,Staying in the USA [Transit]; Steer[Travel],83471.0
97753,ZUCCHERO,GIUSEPPE,09,DOMESTIC,NO,ITALY,SCIARA,ONEIDA NY,Staying in the USA [Transit]; Steer[Travel],83471.0
97754,ZUCCHERO,GIUSEPPE,10,SON,NO,ITALY,MARINEO,NEW YORK,Staying in the USA [Transit]; Steer[Travel],82923.0
97761,ZUCCHERO,MARIAROSA,08,DAUGHTER,NO,ITALY,MARINEO,NEW YORK,Staying in the USA [Transit]; Steer[Travel],82923.0
97765,ZUCCHERO,ROSA,06,DOMESTIC,NO,ITALY,SCIARA,ONEIDA NY,Staying in the USA [Transit]; Steer[Travel],83471.0
97766,ZUCCHERO,SALVATORE,08,DOMESTIC,NO,ITALY,SCIARA,ONEIDA NY,Staying in the USA [Transit]; Steer[Travel],83471.0
98215,ZUMINO,SALVATORE,35,LABORER,NO,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Steer[Travel],83351.0
98222,ZUMMO,ANTONINO,14,FARMER,READ & WRITE,ITALY,GIBELLINA,NEW-ORLEANS,Staying in the USA [Transit]; Steer[Travel],82991.0
98227,ZUMMO,CATERINA,11,FARMER,READ & WRITE,ITALY,POGGIOREALE,BRYAN-TX,Staying in the USA [Transit]; Steer[Travel],82991.0
98228,ZUMMO,CATERINA,42,HOUSEWIFE,NO,ITALY,GIBELLINA,NEW-ORLEANS,Staying in the USA [Transit]; Steer[Travel],82991.0
98229,ZUMMO,FRANCESCO,34,FARMER,READ & WRITE,ITALY,GIBELLINA,NEW-ORLEANS,Staying in the USA [Transit]; Steer[Travel],83135.0
98231,ZUMMO,GIUSEPPA,43,HOUSEWIFE,NO,ITALY,SCIACCA,NEW YORK,Staying in the USA [Transit]; Steer[Travel],83096.0
98232,ZUMMO,GIUSEPPE,17,BARBER,NO,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Steer[Travel],83015.0
98241,ZUMMO,VINCENZO,05,FARMER,READ & WRITE,ITALY,POGGIOREALE,BRYAN-TX,Staying in the USA [Transit]; Steer[Travel],82991.0
98244,ZUMMO,VITO,03,FARMER,NO,ITALY,POGGIOREALE,BRYAN-TX,Staying in the USA [Transit]; Steer[Travel],82991.0
98246,ZUMMO-PUZZUOLO,ANTO.,28,LABORER,NO,ITALY,CASTELVETRANO,KANSAS-CITY,Staying in the USA [Transit]; Steer[Travel],83181.0
98247,ZUMMO-PUZZUOLO,FRANCESCO,Infant in months: 03,FARMER,NO,ITALY,CASTELVETRANO,KANSAS-CITY,Staying in the USA [Transit]; Steer[Travel],83181.0
98248,ZUMMO-PUZZUOLO,GASPARE,06,FARMER,NO,ITALY,CASTELVETRANO,KANSAS-CITY,Staying in the USA [Transit]; Steer[Travel],83181.0
98249,ZUMMO-PUZZUOLO,VITO,03,FARMER,NO,ITALY,CASTELVETRANO,KANSAS-CITY,Staying in the USA [Transit]; Steer[Travel],83181.0
98346,ZUNO,FELICE,39,LABORER,READ & WRITE,ITALY,LIPARI,BROOKLYN NY,Staying in the USA [Transit]; Steer[Travel],83439.0
98347,ZUNO,FRANCESCA,26,DRESSMAKER,NO,ITALY,LIPARI,NEW YORK,Staying in the USA [Transit]; Steer[Travel],83472.0
98348,ZUNO,FRANCESCO,45,LABORER,NO,ITALY,LIPARI,NEW YORK,Staying in the USA [Transit]; Steer[Travel],83472.0
98349,ZUNO,GAETANA,28,DRESSMAKER,NO,ITALY,MELILLI,MIDLETON CT,Staying in the USA [Transit]; Steer[Travel],83472.0
98350,ZUNO,GIOVANNI,15,LABORER,NO,ITALY,LIPARI,BROOKLYN,Staying in the USA [Transit]; Steer[Travel],83188.0
98351,ZUNO,GIUSEPPE,22,LABORER,NO,ITALY,LIPARI,BROOKLYN NY,Staying in the USA [Transit]; Steer[Travel],83439.0
98395,ZUPINGA,VINCENZO,27,SHOEMAKER,READ & WRITE,ITALY,MISTRETTA,NEW YORK,Staying in the USA [Transit]; Steer[Travel],83012.0
98443,ZUPPARDO,GIUSEPPE,48,LABORER,NO,ITALY,CAMPOREALE,NEW-ORLEANS,Staying in the USA [Transit]; Steer[Travel],83122.0
98609,----ZZATI,CARMELA,08,"CHILD, YOUNGSTER",UNKNOWN,ITALY,SCIACCA,NEW YORK,Staying in the USA [Transit]; Steer[Travel],81738.0

In [58]:
#sicilydf.rename(columns = {'CityTownofLastResidence':'Commune'})

,LastName,FirstName,Age,Occupation,Literacy,CountyofOrigin,Commune,DestinationCityTown,TransitTravelCompartment,ManifestID
3,BUONGIORNO,ANTONIO,49,BLACKSMITH,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0
4,BUONGIORNO,GIUSEPPE,60,BLACKSMITH,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0
5,CARUSO,FRANCESCA,Infant in months: 10,INFANT,NO,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0
6,CARUSO,FRANCESCO,03,"CHILD, YOUNGSTER",NO,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0
7,CARUSO,ROSA,38,WIFE,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0
83,ATTANASIO,GIUSEPPE,21,LABORER,UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],80591.0
118,CORRAO,VINCENZO,23,CARPENTER,UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],80591.0
121,CUBILLO,ROSARIO,40,UNKNOWN,UNKNOWN,ITALY,MESSINA,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],63.0
125,DACQUISTO,LORENZO,22,BLACKSMITH,UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],80591.0
134,DERASE,LUIGI,Unknown,UNKNOWN,UNKNOWN,ITALY,MESSINA,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],63.0
137,DICNCANA,FLAGIO,18,UNKNOWN,UNKNOWN,ITALY,MESSINA,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],63.0
145,GARAFALO,FRANCESCO,33,BLACKSMITH,UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],80591.0
176,MAIORANA,VITO,16,LABORER,UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],80591.0
202,PELLEGRINO,GAETANO,Unknown,UNKNOWN,UNKNOWN,ITALY,MESSINA,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],63.0
217,RICCIO,ANTONIO,Unknown,UNKNOWN,UNKNOWN,ITALY,MESSINA,NEW YORK,Staying in the USA [Transit]; Stowaway [Travel],63.0
250,AGNELLO,ANTONINO,08,"CHILD, YOUNGSTER",UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Cabin Passenger ...,108.0
251,AGNELLO,FRANCESCO,02,"CHILD, YOUNGSTER",UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Cabin Passenger ...,108.0
252,AGNELLO,FRANCESCO,39,COUNTRY MAN,UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Cabin Passenger ...,108.0
253,AGNELLO,ISIDORO,06,"CHILD, YOUNGSTER",UNKNOWN,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Cabin Passenger ...,108.0
254,AGOSTA,ALFONSO,20,FARMER,UNKNOWN,ITALY,POGGIOREALE,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
255,AGOSTA,GIUSEPPE,24,FARMER,NO,ITALY,POGGIOREALE,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
259,AMATO,GAETANO,28,FARMER,UNKNOWN,ITALY,POGGIOREALE,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
260,AMORE,CARLO,22,CARPENTER,UNKNOWN,ITALY,PALERMO,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
261,ANASTASI,PIETRO,34,DOMESTIC,UNKNOWN,ITALY,MESSINA,NEW YORK,Staying in the USA [Transit]; Cabin Passenger ...,468.0
264,AVVOCATO,ROSARIO,38,FARMER,NO,ITALY,SALAPARUTA,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
268,BARONE,FRANCESCA,07,"CHILD, YOUNGSTER",UNKNOWN,ITALY,CACCAMO,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
269,BARONE,VINCENZA,10,"CHILD, YOUNGSTER",UNKNOWN,ITALY,CACCAMO,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
273,BASILE,NUNZIATA,21,LABORER,UNKNOWN,ITALY,USTICA,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
274,BENFANTE,ANTONINO,24,CARTER,READ & WRITE,ITALY,MENFI,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
277,BIONDOLILLO,LUCIA,21,HOUSE WOMAN,UNKNOWN,ITALY,ALIA,NEW-ORLEANS-LA,Staying in the USA [Transit]; Cabin Passenger ...,476.0
...,...,...,...,...,...,...,...,...,...,...
97748,ZUCCHERO,CONCETTA,29,FARMER,UNKNOWN,ITALY,MARINEO,NEW YORK,Staying in the USA [Transit]; Steer[Travel],81352.0
97749,ZUCCHERO,CONCETTA,36,FARMER,NO,ITALY,MARINEO,NEW YORK,Staying in the USA [Transit]; Steer[Travel],82923.0
97752,ZUCCHERO,GIUSEPPA,12,DOMESTIC,NO,ITALY,SCIARA,ONEIDA NY,Staying in the USA [Transit]; Steer[Travel],83471.0
97753,ZUCCHERO,GIUSEPPE,09,DOMESTIC,NO,ITALY,SCIARA,ONEIDA NY,Staying in the USA [Transit]; Steer[Travel],83471.0
97754,ZUCCHERO,GIUSEPPE,10,SON,NO,ITALY,MARINEO,NEW YORK,Staying in the USA [Transit]; Steer[Travel],82923.0
97761,ZUCCHERO,MARIAROSA,08,DAUGHTER,NO,ITALY,MARINEO,NEW YORK,Staying in the USA [Transit]; Steer[Travel],82923.0
97765,ZUCCHERO,ROSA,06,DOMESTIC,NO,ITALY,SCIARA,ONEIDA NY,Staying in the USA [Transit]; Steer[Travel],83471.0
97766,ZUCCHERO,SALVATORE,08,DOMESTIC,NO,ITALY,SCIARA,ONEIDA NY,Staying in the USA [Transit]; Steer[Travel],83471.0
98215,ZUMINO,SALVATORE,35,LABORER,NO,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Steer[Travel],83351.0
98222,ZUMMO,ANTONINO,14,FARMER,READ & WRITE,ITALY,GIBELLINA,NEW-ORLEANS,Staying in the USA [Transit]; Steer[Travel],82991.0
98227,ZUMMO,CATERINA,11,FARMER,READ & WRITE,ITALY,POGGIOREALE,BRYAN-TX,Staying in the USA [Transit]; Steer[Travel],82991.0
98228,ZUMMO,CATERINA,42,HOUSEWIFE,NO,ITALY,GIBELLINA,NEW-ORLEANS,Staying in the USA [Transit]; Steer[Travel],82991.0
98229,ZUMMO,FRANCESCO,34,FARMER,READ & WRITE,ITALY,GIBELLINA,NEW-ORLEANS,Staying in the USA [Transit]; Steer[Travel],83135.0
98231,ZUMMO,GIUSEPPA,43,HOUSEWIFE,NO,ITALY,SCIACCA,NEW YORK,Staying in the USA [Transit]; Steer[Travel],83096.0
98232,ZUMMO,GIUSEPPE,17,BARBER,NO,ITALY,PALERMO,NEW YORK,Staying in the USA [Transit]; Steer[Travel],83015.0
98241,ZUMMO,VINCENZO,05,FARMER,READ & WRITE,ITALY,POGGIOREALE,BRYAN-TX,Staying in the USA [Transit]; Steer[Travel],82991.0
98244,ZUMMO,VITO,03,FARMER,NO,ITALY,POGGIOREALE,BRYAN-TX,Staying in the USA [Transit]; Steer[Travel],82991.0
98246,ZUMMO-PUZZUOLO,ANTO.,28,LABORER,NO,ITALY,CASTELVETRANO,KANSAS-CITY,Staying in the USA [Transit]; Steer[Travel],83181.0
98247,ZUMMO-PUZZUOLO,FRANCESCO,Infant in months: 03,FARMER,NO,ITALY,CASTELVETRANO,KANSAS-CITY,Staying in the USA [Transit]; Steer[Travel],83181.0
98248,ZUMMO-PUZZUOLO,GASPARE,06,FARMER,NO,ITALY,CASTELVETRANO,KANSAS-CITY,Staying in the USA [Transit]; Steer[Travel],83181.0
98249,ZUMMO-PUZZUOLO,VITO,03,FARMER,NO,ITALY,CASTELVETRANO,KANSAS-CITY,Staying in the USA [Transit]; Steer[Travel],83181.0
98346,ZUNO,FELICE,39,LABORER,READ & WRITE,ITALY,LIPARI,BROOKLYN NY,Staying in the USA [Transit]; Steer[Travel],83439.0
98347,ZUNO,FRANCESCA,26,DRESSMAKER,NO,ITALY,LIPARI,NEW YORK,Staying in the USA [Transit]; Steer[Travel],83472.0
98348,ZUNO,FRANCESCO,45,LABORER,NO,ITALY,LIPARI,NEW YORK,Staying in the USA [Transit]; Steer[Travel],83472.0
98349,ZUNO,GAETANA,28,DRESSMAKER,NO,ITALY,MELILLI,MIDLETON CT,Staying in the USA [Transit]; Steer[Travel],83472.0
98350,ZUNO,GIOVANNI,15,LABORER,NO,ITALY,LIPARI,BROOKLYN,Staying in the USA [Transit]; Steer[Travel],83188.0
98351,ZUNO,GIUSEPPE,22,LABORER,NO,ITALY,LIPARI,BROOKLYN NY,Staying in the USA [Transit]; Steer[Travel],83439.0
98395,ZUPINGA,VINCENZO,27,SHOEMAKER,READ & WRITE,ITALY,MISTRETTA,NEW YORK,Staying in the USA [Transit]; Steer[Travel],83012.0
98443,ZUPPARDO,GIUSEPPE,48,LABORER,NO,ITALY,CAMPOREALE,NEW-ORLEANS,Staying in the USA [Transit]; Steer[Travel],83122.0
98609,----ZZATI,CARMELA,08,"CHILD, YOUNGSTER",UNKNOWN,ITALY,SCIACCA,NEW YORK,Staying in the USA [Transit]; Steer[Travel],81738.0

In [20]:
sicilydf = pd.merge(sicilydf,communes,how='left',left_on='CityTownofLastResidence',right_on='Commune')

In [25]:
sicilydf = sicilydf.drop(['Population','Commune'],axis='columns')

In [39]:
df['CityTownofLastResidence'].isna().value_counts()

False    768132
True        742
Name: CityTownofLastResidence, dtype: int64

In [26]:
sicilydf.head()

,LastName,FirstName,Age,Occupation,Literacy,CountyofOrigin,CityTownofLastResidence,DestinationCityTown,TransitTravelCompartment,ManifestID,Province
0,BUONGIORNO,ANTONIO,49,BLACKSMITH,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0,Agrigento
1,BUONGIORNO,GIUSEPPE,60,BLACKSMITH,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0,Agrigento
2,CARUSO,FRANCESCA,Infant in months: 10,INFANT,NO,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0,Agrigento
3,CARUSO,FRANCESCO,03,"CHILD, YOUNGSTER",NO,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0,Agrigento
4,CARUSO,ROSA,38,WIFE,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236.0,Agrigento

In [27]:
sicilydf['Province'].value_counts()

Palermo          21977
Messina           6560
Agrigento         6076
Enna              1713
Trapani           1316
Caltanissetta     1099
Catania            560
Siracusa           354
Ragusa              70
Name: Province, dtype: int64

In [40]:
df['Literacy'].value_counts()

UNKNOWN           456197
NO                193426
READ & WRITE      119038
Undefined Code         2
N                      1
Name: Literacy, dtype: int64

In [43]:
df.to_csv('./data/italians_to_america.csv')

In [33]:
manifests = pd.read_csv('data/manifest_list_1855_1900.csv')
manifests.head()

   ManifestID   ShipName                    Port     Arrival
0           1   MASSILIA     MARSEILLES & NAPLES  04/04/1894
1           4     ITALIA                  NAPLES  04/07/1894
2           6   TEUTONIC  LIVERPOOL & QUEENSTOWN  04/15/1897
3           8  BRITANNIA     MARSEILLES & NAPLES  02/24/1890
4          11   CASTALIA                   HAVRE  11/08/1880

In [31]:
sicilydf['ManifestID'] = sicilydf['ManifestID'].astype('int')

In [35]:
sicilydf = pd.merge(sicilydf, manifests, how='left', on='ManifestID')

In [36]:
sicilydf.head()

,LastName,FirstName,Age,Occupation,Literacy,CountyofOrigin,CityTownofLastResidence,DestinationCityTown,TransitTravelCompartment,ManifestID,Province,ShipName,Port,Arrival
0,BUONGIORNO,ANTONIO,49,BLACKSMITH,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236,Agrigento,EMS,NAPLES,12/29/1892
1,BUONGIORNO,GIUSEPPE,60,BLACKSMITH,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236,Agrigento,EMS,NAPLES,12/29/1892
2,CARUSO,FRANCESCA,Infant in months: 10,INFANT,NO,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236,Agrigento,EMS,NAPLES,12/29/1892
3,CARUSO,FRANCESCO,03,"CHILD, YOUNGSTER",NO,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236,Agrigento,EMS,NAPLES,12/29/1892
4,CARUSO,ROSA,38,WIFE,READ & WRITE,ITALY,SCIACCA,NEW YORK,Return trip to USA - non US Citizen [Transit];...,82236,Agrigento,EMS,NAPLES,12/29/1892

In [37]:
sicilydf['Age'].value_counts()

24                      1327
23                      1300
22                      1245
25                      1197
26                      1175
16                      1102
27                      1047
21                      1028
17                      1023
28                      1000
30                       964
29                       906
32                       862
15                       854
11                       851
20                       820
07                       800
34                       778
03                       769
14                       739
01                       734
08                       730
33                       716
04                       714
18                       711
35                       709
31                       707
06                       701
10                       700
36                       676
                        ...
Infant in months: 11     147
56                       143
58                       129
57                       126
Infant in months: 10     110
Undefined Code           109
59                       104
60                       102
Infant in months: 08      73
Infant in months: 06      70
Infant in months: 01      66
Infant in months: 07      62
Infant in months: 04      61
Infant in months: 02      61
Infant in months: 09      55
61                        51
Infant in months: 05      50
63                        47
64                        46
62                        44
Infant in months: 03      42
65                        30
66                        29
68                        21
67                        20
71                        20
70                        18
80                        11
72                        11
78                         2
Name: Age, Length: 86, dtype: int64

In [38]:
sicilydf.to_csv('./data/sicily_passengers.csv')